from io import BytesIO
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib import colors


def generate_pdf(report_text, repo_name):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        textColor=colors.HexColor("#1E3A8A"),
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        textColor=colors.HexColor("#2563EB"),
        spaceAfter=12
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        leading=18,
        spaceAfter=6
    )

    content = []

    # -----------------------------
    # COVER PAGE
    # -----------------------------

    content.append(
        Paragraph(
            "GitHub Repository Intelligence Report",
            title_style
        )
    )

    content.append(Spacer(1, 30))

    content.append(
        Paragraph(
            f"<b>Repository:</b> {repo_name}",
            heading_style
        )
    )

    content.append(
        Paragraph(
            "<b>Generated By:</b> AI GitHub Multi-Agent Analyzer",
            body_style
        )
    )

    content.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d %B %Y')}",
            body_style
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            """
            This report was automatically generated using a
            LangGraph-based Multi-Agent AI System.
            The analysis includes repository intelligence,
            technology stack analysis, interview preparation,
            project review and recommendations.
            """,
            body_style
        )
    )

    content.append(PageBreak())

    # -----------------------------
    # MAIN REPORT
    # -----------------------------

    for line in report_text.split("\n"):

        line = line.strip()

        if not line:
            continue

        # H1

        if line.startswith("# "):

            content.append(
                Paragraph(
                    line.replace("# ", ""),
                    title_style
                )
            )

            continue

        # H2

        if line.startswith("## "):

            content.append(
                Paragraph(
                    line.replace("## ", ""),
                    heading_style
                )
            )

            continue

        # H3

        if line.startswith("### "):

            content.append(
                Paragraph(
                    line.replace("### ", ""),
                    heading_style
                )
            )

            continue

        # Bullet Points

        if line.startswith("- "):

            content.append(
                Paragraph(
                    f"• {line[2:]}",
                    body_style
                )
            )

            continue

        # Normal Text

        content.append(
            Paragraph(
                line,
                body_style
            )
        )

    doc.build(content)

    buffer.seek(0)

    return buffer
